DELETE http://localhost:3003/api/blogs/669bb3842f88462277da926d HTTP/1.1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpdW1pIiwiaWQiOiI2NjliYjM0MDE0YTI0Njg1MWZlZjJhMDciLCJpYXQiOjE3MjE0ODI3NjAsImV4cCI6MTcyMTQ4NjM2MH0.oCtaCUvb7GiK_Oz1-rLKdZvD5NV6XyqRZA7UuGyHHms
