# fly.toml app configuration file generated for mooc-phonebook-server on 2024-07-18T01:23:18+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mooc-phonebook-server'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
